# Generated by Django 5.1 on 2024-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
