# Generated by Django 4.2.15 on 2024-08-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursestudent_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('E', 'Excused'), ('A', 'Absent')], default='A', max_length=2)),
                ('course_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursestudent')),
            ],
        ),
    ]
