# Generated by Django 4.2.15 on 2024-08-24 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='material_curso',
            field=models.CharField(default='libros,web', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
