# Generated by Django 4.2.15 on 2024-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_end_date_course_material_curso_course_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='juan', max_length=30, unique=True),
        ),
    ]
