# Generated by Django 4.2.15 on 2024-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='juan', max_length=30, unique=True),
        ),
    ]
